name: Test Python 🐍 distributions

on:
  push:

jobs:
  build:
    name: Test python files in tests folder 
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest

